// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0aEgC6HblXpItTsqubEgywJywfC6OJB0',
    appId: '1:632213123807:web:4dfd453b0c2b74999baf6a',
    messagingSenderId: '632213123807',
    projectId: 'flutter-tts-f316e',
    authDomain: 'flutter-tts-f316e.firebaseapp.com',
    databaseURL: 'https://flutter-tts-f316e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-tts-f316e.firebasestorage.app',
    measurementId: 'G-225GYSZRF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDafR8sw2DbGQz-HEJx61iZYcxtxRloyaM',
    appId: '1:632213123807:android:a1b804ffc2e0c9319baf6a',
    messagingSenderId: '632213123807',
    projectId: 'flutter-tts-f316e',
    databaseURL: 'https://flutter-tts-f316e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-tts-f316e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmcGzysJGeai7Dr_du6lsNlyutKqzS5yI',
    appId: '1:632213123807:ios:d51638ac3834bf439baf6a',
    messagingSenderId: '632213123807',
    projectId: 'flutter-tts-f316e',
    databaseURL: 'https://flutter-tts-f316e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-tts-f316e.firebasestorage.app',
    iosClientId: '632213123807-cicj7e4cupe54qs11okjqf1ekhto7tsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmcGzysJGeai7Dr_du6lsNlyutKqzS5yI',
    appId: '1:632213123807:ios:d51638ac3834bf439baf6a',
    messagingSenderId: '632213123807',
    projectId: 'flutter-tts-f316e',
    databaseURL: 'https://flutter-tts-f316e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-tts-f316e.firebasestorage.app',
    iosClientId: '632213123807-cicj7e4cupe54qs11okjqf1ekhto7tsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0aEgC6HblXpItTsqubEgywJywfC6OJB0',
    appId: '1:632213123807:web:2b89627d04c972019baf6a',
    messagingSenderId: '632213123807',
    projectId: 'flutter-tts-f316e',
    authDomain: 'flutter-tts-f316e.firebaseapp.com',
    databaseURL: 'https://flutter-tts-f316e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-tts-f316e.firebasestorage.app',
    measurementId: 'G-DG31580YQV',
  );
}
